name: flutter_add_calendar
description: Add event to device Calendar for Awesome Flutter Application
version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: flutteraddcalendar.fluttervn.io.flutteraddcalendar
    pluginClass: FlutterAddCalendarPlugin